extern const GeoLayout bbb_area_1_geo[];
extern const GeoLayout bbb_dl_Room01_geo[];
extern const GeoLayout bbb_dl_Room02_geo[];
extern const GeoLayout bbb_dl_Room03_geo[];
extern const GeoLayout bbb_dl_Room04_geo[];
extern const GeoLayout bbb_dl_Room05_geo[];
extern const GeoLayout bbb_dl_Room07__1_2__geo[];
extern const GeoLayout bbb_dl_Room08__2_3__geo[];
extern const GeoLayout bbb_dl_Room09__3_4__geo[];
extern const GeoLayout bbb_dl_Room10__4_5__geo[];
extern const GeoLayout bbb_area_1[];
extern const Collision bbb_area_1_collision[];
extern const u8 bbb_area_1_collision_rooms[];
extern const MacroObject bbb_area_1_macro_objs[];
extern const GeoLayout bbb_area_2_geo[];
extern const GeoLayout bbb_dl_Room_06_geo[];
extern const GeoLayout bbb_area_2[];
extern const Collision bbb_area_2_collision[];
extern const u8 bbb_area_2_collision_rooms[];
extern const MacroObject bbb_area_2_macro_objs[];
extern Lights1 bbb_dl_f3dlite_material_044_lights;
extern u8 bbb_dl_th_kiyuka_ci8[];
extern u8 bbb_dl_th_kiyuka_ci8_pal_rgba16[];
extern u8 bbb_dl_th_teppan_ci8[];
extern u8 bbb_dl_th_teppan_ci8_pal_rgba16[];
extern u8 bbb_dl_th_yuka01_ci4[];
extern u8 bbb_dl_th_yuka01_ci4_pal_rgba16[];
extern u8 bbb_dl_kikiki_ci8[];
extern u8 bbb_dl_kikiki_ci8_pal_rgba16[];
extern u8 bbb_dl_th_daikabe_ci8[];
extern u8 bbb_dl_th_daikabe_ci8_pal_rgba16[];
extern u8 bbb_dl_th_kabe01_ci8[];
extern u8 bbb_dl_th_kabe01_ci8_pal_rgba16[];
extern u8 bbb_dl_th_renga_ci8[];
extern u8 bbb_dl_th_renga_ci8_pal_rgba16[];
extern u8 bbb_dl_exl_maku_32x64_ci8[];
extern u8 bbb_dl_exl_maku_32x64_ci8_pal_rgba16[];
extern u8 bbb_dl_th_pic_t_1_rgba16[];
extern u8 bbb_dl_th_tesuri00_ci8[];
extern u8 bbb_dl_th_tesuri00_ci8_pal_rgba16[];
extern u8 bbb_dl_th_pic_t_2_rgba16[];
extern u8 bbb_dl_exl_cpt_32x64_ci8[];
extern u8 bbb_dl_exl_cpt_32x64_ci8_pal_rgba16[];
extern u8 bbb_dl_kikiki_ci8_copy[];
extern u8 bbb_dl_kikiki_ci8_pal_rgba16_copy[];
extern u8 bbb_dl_exl_mr_ci4[];
extern u8 bbb_dl_exl_mr_ci4_pal_rgba16[];
extern u8 bbb_dl_th_hasira_ci8[];
extern u8 bbb_dl_th_hasira_ci8_pal_rgba16[];
extern u8 bbb_dl_th_huti00_ci8[];
extern u8 bbb_dl_th_huti00_ci8_pal_rgba16[];
extern u8 bbb_dl_th_kabe01_ci8_copy[];
extern u8 bbb_dl_th_kabe01_ci8_pal_rgba16_copy[];
extern u8 bbb_dl_exl_yuka00_64x32_ci8[];
extern u8 bbb_dl_exl_yuka00_64x32_ci8_pal_rgba16[];
extern Vtx bbb_dl_Ignore_Collision_mesh_layer_1_vtx_0[78];
extern Gfx bbb_dl_Ignore_Collision_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_Ignore_Collision_mesh_layer_1_vtx_1[9];
extern Gfx bbb_dl_Ignore_Collision_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_Ignore_Collision_mesh_layer_1_vtx_2[40];
extern Gfx bbb_dl_Ignore_Collision_mesh_layer_1_tri_2[];
extern Vtx bbb_dl_r0_node_mesh_layer_1_vtx_0[55];
extern Gfx bbb_dl_r0_node_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r0_node_mesh_layer_1_vtx_1[32];
extern Gfx bbb_dl_r0_node_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_r0_node_mesh_layer_1_vtx_2[8];
extern Gfx bbb_dl_r0_node_mesh_layer_1_tri_2[];
extern Vtx bbb_dl_r0_node_mesh_layer_1_vtx_3[59];
extern Gfx bbb_dl_r0_node_mesh_layer_1_tri_3[];
extern Vtx bbb_dl_r0_node_mesh_layer_1_vtx_4[80];
extern Gfx bbb_dl_r0_node_mesh_layer_1_tri_4[];
extern Vtx bbb_dl_Ignore_Collision_001_mesh_layer_1_vtx_0[12];
extern Gfx bbb_dl_Ignore_Collision_001_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_Ignore_Collision_001_mesh_layer_1_vtx_1[28];
extern Gfx bbb_dl_Ignore_Collision_001_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_r1_node_mesh_layer_1_vtx_0[124];
extern Gfx bbb_dl_r1_node_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r1_node_mesh_layer_1_vtx_1[72];
extern Gfx bbb_dl_r1_node_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_Ignore_Collision_002_mesh_layer_1_vtx_0[32];
extern Gfx bbb_dl_Ignore_Collision_002_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r2_node_mesh_layer_1_vtx_0[56];
extern Gfx bbb_dl_r2_node_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r2_node_mesh_layer_1_vtx_1[8];
extern Gfx bbb_dl_r2_node_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_r2_node_mesh_layer_1_vtx_2[56];
extern Gfx bbb_dl_r2_node_mesh_layer_1_tri_2[];
extern Vtx bbb_dl_r2_node_mesh_layer_1_vtx_3[102];
extern Gfx bbb_dl_r2_node_mesh_layer_1_tri_3[];
extern Vtx bbb_dl_Ignore_Collision_003_mesh_layer_1_vtx_0[12];
extern Gfx bbb_dl_Ignore_Collision_003_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_Ignore_Collision_003_mesh_layer_1_vtx_1[24];
extern Gfx bbb_dl_Ignore_Collision_003_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_r3_node_mesh_layer_1_vtx_0[54];
extern Gfx bbb_dl_r3_node_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r3_node_mesh_layer_1_vtx_1[12];
extern Gfx bbb_dl_r3_node_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_r3_node_mesh_layer_1_vtx_2[56];
extern Gfx bbb_dl_r3_node_mesh_layer_1_tri_2[];
extern Vtx bbb_dl_r3_node_mesh_layer_1_vtx_3[81];
extern Gfx bbb_dl_r3_node_mesh_layer_1_tri_3[];
extern Vtx bbb_dl_r3_node_001_mesh_layer_1_vtx_0[14];
extern Gfx bbb_dl_r3_node_001_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_0[44];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_1[16];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_2[26];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_2[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_3[159];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_3[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_4[16];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_4[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_5[4];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_5[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_6[58];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_6[];
extern Vtx bbb_dl_r4_node_mesh_layer_1_vtx_7[4];
extern Gfx bbb_dl_r4_node_mesh_layer_1_tri_7[];
extern Vtx bbb_dl_r4_node_mesh_layer_4_vtx_0[16];
extern Gfx bbb_dl_r4_node_mesh_layer_4_tri_0[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_1_vtx_0[21];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1_tri_0[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_1_vtx_1[268];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1_tri_1[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_1_vtx_2[40];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1_tri_2[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_1_vtx_3[102];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1_tri_3[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_1_vtx_4[104];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1_tri_4[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_1_vtx_5[291];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1_tri_5[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_1_vtx_6[80];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1_tri_6[];
extern Vtx bbb_dl_r0_node_002_mesh_layer_5_vtx_0[4];
extern Gfx bbb_dl_r0_node_002_mesh_layer_5_tri_0[];
extern Gfx mat_bbb_dl_f3dlite_material_036[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_036[];
extern Gfx mat_bbb_dl_f3dlite_material_037[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_037[];
extern Gfx mat_bbb_dl_f3dlite_material_039[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_039[];
extern Gfx mat_bbb_dl_f3dlite_material_035[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_035[];
extern Gfx mat_bbb_dl_f3dlite_material_038[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_038[];
extern Gfx mat_bbb_dl_f3dlite_material_040[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_040[];
extern Gfx mat_bbb_dl_f3dlite_material_041[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_041[];
extern Gfx mat_bbb_dl_f3dlite_material_042[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_042[];
extern Gfx mat_bbb_dl_f3dlite_material_043[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_043[];
extern Gfx mat_bbb_dl_f3dlite_material_044[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_044[];
extern Gfx mat_bbb_dl_f3dlite_material_045[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_045[];
extern Gfx mat_bbb_dl_f3dlite_material_048[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_048[];
extern Gfx mat_bbb_dl_f3dlite_material_049[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_049[];
extern Gfx mat_bbb_dl_f3dlite_material_050[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_050[];
extern Gfx mat_bbb_dl_f3dlite_material_051[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_051[];
extern Gfx mat_bbb_dl_f3dlite_material_052[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_052[];
extern Gfx mat_bbb_dl_f3dlite_material_053[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_053[];
extern Gfx mat_bbb_dl_f3dlite_material_054[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_054[];
extern Gfx mat_bbb_dl_f3dlite_material_055[];
extern Gfx mat_revert_bbb_dl_f3dlite_material_055[];
extern Gfx bbb_dl_Ignore_Collision_mesh_layer_1[];
extern Gfx bbb_dl_r0_node_mesh_layer_1[];
extern Gfx bbb_dl_Ignore_Collision_001_mesh_layer_1[];
extern Gfx bbb_dl_r1_node_mesh_layer_1[];
extern Gfx bbb_dl_Ignore_Collision_002_mesh_layer_1[];
extern Gfx bbb_dl_r2_node_mesh_layer_1[];
extern Gfx bbb_dl_Ignore_Collision_003_mesh_layer_1[];
extern Gfx bbb_dl_r3_node_mesh_layer_1[];
extern Gfx bbb_dl_r3_node_001_mesh_layer_1[];
extern Gfx bbb_dl_r4_node_mesh_layer_1[];
extern Gfx bbb_dl_r4_node_mesh_layer_4[];
extern Gfx bbb_dl_r0_node_002_mesh_layer_1[];
extern Gfx bbb_dl_r0_node_002_mesh_layer_5[];
extern Gfx bbb_dl_material_revert_render_settings[];
