#include "src/game/envfx_snow.h"

const GeoLayout castle_inside_area_4_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(6, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, castle_inside_dl_Room1_geo),
			GEO_BRANCH(1, castle_inside_dl_Room2_geo),
			GEO_BRANCH(1, castle_inside_dl_Room3_geo),
			GEO_BRANCH(1, castle_inside_dl_Room4__1_2__geo),
			GEO_BRANCH(1, castle_inside_dl_Room5__2_3__geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_Room1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Ignore_Collision_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Ignore_Collision_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_r0_node_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_Room2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Ignore_Collision_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Ignore_Collision_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Ignore_Collision_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_r1_node_mesh_layer_1),
		GEO_ASM(0, geo_painting_update),
		GEO_ASM(PAINTING_ID(0, 3), geo_painting_draw),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_Room3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Ignore_Collision_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Ignore_Collision_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_r2_node_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_r2_node_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_r2_node_mesh_layer_1),
		GEO_ASM(0, geo_painting_update),
		GEO_ASM(PAINTING_ID(1, 3), geo_painting_draw),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_Room4__1_2__geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Ignore_Collision_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Ignore_Collision_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_r0_node_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Ignore_Collision_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Ignore_Collision_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_r1_node_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Ignore_Collision_002_mesh_layer_5),
		GEO_ASM(0, geo_painting_update),
		GEO_ASM(PAINTING_ID(0, 3), geo_painting_draw),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_Room5__2_3__geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Ignore_Collision_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Ignore_Collision_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_r1_node_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Ignore_Collision_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Ignore_Collision_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_r2_node_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Ignore_Collision_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_r2_node_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_r2_node_mesh_layer_5),
		GEO_ASM(0, geo_painting_update),
		GEO_ASM(PAINTING_ID(0, 3), geo_painting_draw),
		GEO_ASM(PAINTING_ID(1, 3), geo_painting_draw),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_area_4[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_FREE_ROAM, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_inside_area_4_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
