#include "levels/castle_inside/area_4/collision.inc.c"
#include "levels/castle_inside/area_4/room.inc.c"
#include "levels/castle_inside/area_4/macro.inc.c"
#include "levels/castle_inside/area_4/spline.inc.c"
#include "levels/castle_inside/model.inc.c"
