extern const GeoLayout ccc_area_1_geo[];
extern const GeoLayout ccc_area_1[];
extern const Collision ccc_area_1_collision[];
extern const MacroObject ccc_area_1_macro_objs[];
extern const GeoLayout ccc_area_2_geo[];
extern const GeoLayout ccc_area_2[];
extern const Collision ccc_area_2_collision[];
extern const MacroObject ccc_area_2_macro_objs[];
extern u8 ccc_dl_nagare_no_alpha_rgba32[];
extern u8 ccc_dl_nagare_kiwa_no_alpha_rgba32[];
extern u8 ccc_dl_kusari_32x32_ci4[];
extern u8 ccc_dl_kusari_32x32_ci4_pal_rgba16[];
extern u8 ccc_dl_water_ci4[];
extern u8 ccc_dl_water_ci4_pal_rgba16[];
extern u8 ccc_dl_ice_64x64_ci4[];
extern u8 ccc_dl_ice_64x64_ci4_pal_rgba16[];
extern u8 ccc_dl_fence_ci8[];
extern u8 ccc_dl_fence_ci8_pal_rgba16[];
extern u8 ccc_dl_ishi_ci8[];
extern u8 ccc_dl_ishi_ci8_pal_rgba16[];
extern u8 ccc_dl_saku_ci8[];
extern u8 ccc_dl_saku_ci8_pal_rgba16[];
extern u8 ccc_dl_bokasi_flat_rgba32[];
extern u8 ccc_dl_nagare_no_alpha_rgba32_copy[];
extern Vtx ccc_dl_Ignore_Collision_mesh_layer_5_vtx_0[13];
extern Gfx ccc_dl_Ignore_Collision_mesh_layer_5_tri_0[];
extern Vtx ccc_dl_Ignore_Collision_mesh_layer_5_vtx_1[48];
extern Gfx ccc_dl_Ignore_Collision_mesh_layer_5_tri_1[];
extern Vtx ccc_dl_Ignore_Collision_001_mesh_layer_4_vtx_0[16];
extern Gfx ccc_dl_Ignore_Collision_001_mesh_layer_4_tri_0[];
extern Vtx ccc_dl_Ignore_Collision_001_mesh_layer_5_vtx_0[7];
extern Gfx ccc_dl_Ignore_Collision_001_mesh_layer_5_tri_0[];
extern Vtx ccc_dl_Ignore_Collision_001_mesh_layer_1_vtx_0[14];
extern Gfx ccc_dl_Ignore_Collision_001_mesh_layer_1_tri_0[];
extern Vtx ccc_dl_r0_node_mesh_layer_1_vtx_0[1323];
extern Gfx ccc_dl_r0_node_mesh_layer_1_tri_0[];
extern Vtx ccc_dl_r0_node_mesh_layer_1_vtx_1[473];
extern Gfx ccc_dl_r0_node_mesh_layer_1_tri_1[];
extern Vtx ccc_dl_r0_node_mesh_layer_4_vtx_0[4];
extern Gfx ccc_dl_r0_node_mesh_layer_4_tri_0[];
extern Vtx ccc_dl_r0_node_mesh_layer_4_vtx_1[152];
extern Gfx ccc_dl_r0_node_mesh_layer_4_tri_1[];
extern Vtx ccc_dl_Ignore_Collision_002_mesh_layer_1_vtx_0[344];
extern Gfx ccc_dl_Ignore_Collision_002_mesh_layer_1_tri_0[];
extern Vtx ccc_dl_Ignore_Collision_002_mesh_layer_5_vtx_0[28];
extern Gfx ccc_dl_Ignore_Collision_002_mesh_layer_5_tri_0[];
extern Vtx ccc_dl_r0_node_001_mesh_layer_5_vtx_0[127];
extern Gfx ccc_dl_r0_node_001_mesh_layer_5_tri_0[];
extern Gfx mat_ccc_dl_f3dlite_material_001[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_001[];
extern Gfx mat_ccc_dl_f3dlite_material_002[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_002[];
extern Gfx mat_ccc_dl_f3dlite_material_038[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_038[];
extern Gfx mat_ccc_dl_f3dlite_material_042[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_042[];
extern Gfx mat_ccc_dl_f3dlite_material_036[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_036[];
extern Gfx mat_ccc_dl_f3dlite_material_035[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_035[];
extern Gfx mat_ccc_dl_f3dlite_material_037[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_037[];
extern Gfx mat_ccc_dl_f3dlite_material_041[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_041[];
extern Gfx mat_ccc_dl_f3dlite_material_003[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_003[];
extern Gfx mat_ccc_dl_f3dlite_material_004[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_004[];
extern Gfx mat_ccc_dl_f3dlite_material_007[];
extern Gfx mat_revert_ccc_dl_f3dlite_material_007[];
extern Gfx ccc_dl_Ignore_Collision_mesh_layer_5[];
extern Gfx ccc_dl_Ignore_Collision_001_mesh_layer_4[];
extern Gfx ccc_dl_Ignore_Collision_001_mesh_layer_5[];
extern Gfx ccc_dl_Ignore_Collision_001_mesh_layer_1[];
extern Gfx ccc_dl_r0_node_mesh_layer_1[];
extern Gfx ccc_dl_r0_node_mesh_layer_4[];
extern Gfx ccc_dl_Ignore_Collision_002_mesh_layer_1[];
extern Gfx ccc_dl_Ignore_Collision_002_mesh_layer_5[];
extern Gfx ccc_dl_r0_node_001_mesh_layer_5[];
extern Gfx ccc_dl_material_revert_render_settings[];
