#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"
#include "levels/ccc/texture.inc.c"
#include "levels/ccc/area_1/light.inc.c"
#include "levels/ccc/tilting_square_platform/model.inc.c"
#include "levels/ccc/tilting_square_platform/collision.inc.c"
#include "levels/ccc/leveldata.inc.c"

#include "levels/ccc/moving_octagonal_mesh_platform/collision.inc.c"
#include "levels/ccc/moving_octagonal_mesh_platform/model.inc.c"
#include "levels/ccc/ccc_huge_ice_block_lift/collision.inc.c"
#include "levels/ccc/ccc_huge_ice_block_lift/model.inc.c"
#include "levels/ccc/ccc_ice_c/collision.inc.c"
#include "levels/ccc/ccc_ice_c/model.inc.c"
#include "levels/ccc/ccc_ice_b/collision.inc.c"
#include "levels/ccc/ccc_ice_b/model.inc.c"
#include "levels/ccc/ccc_ice_a/collision.inc.c"
#include "levels/ccc/ccc_ice_a/model.inc.c"
#include "levels/ccc/ccc_boss_squish/collision.inc.c"